name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build with Maven
      run: mvn clean install -f MyWebApp/pom.xml -DskipTests
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=my-org
          -Dsonar.projectKey=my-Java-web-app
      env:
        SONAR_TOKEN: sqa_9045114cc3b6182ea8e78dd49f619e12f177c2c2

        SONAR_HOST_URL: http://ec2-13-59-90-124.us-east-2.compute.amazonaws.com:9000
   
